# platform :ios, '8.0'

use_frameworks!


target 'Rick&Morty' do

  pod 'Firebase/Auth'

pod 'FirebaseUI/Auth'
pod 'FirebaseUI/Google'
pod 'FirebaseUI/Facebook'
pod 'FirebaseUI/OAuth' # Used for Sign in with Apple, Twitter, etc
pod 'FirebaseUI/Phone'

  pod 'Kingfisher', :git => 'https://github.com/onevcat/Kingfisher.git'

end
